layout_spectrum: 0.4873900832608342
favicon: null
name: LOUD Kingdom
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.4127360582351685
  lightness: 0.7574468
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#211f20'
    - '#ffffff'
    - '#dbdbdb'
    - '#868686'
    - '#535353'
typography_spectrum: 0.64124
