name: LOUD Kingdom
favicon: null
layout_spectrum: 0.4873900832608342
typography_spectrum: 0.68282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211f20'
    - '#ffffff'
    - '#dbdbdb'
    - '#868686'
    - '#535353'
  brandStrength: 0.41273605823516846
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
